<a href="https://colab.research.google.com/github/fThAbhishek-Pandey/numpy-series/blob/main/fthses_01_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array // vector
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D Or  matrics
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
#3D or tensor
c= np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
#bool
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

2nd method to create array

In [6]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

create utility array with inisialize

In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.random
np.random.random((3,4))

array([[0.87316573, 0.76388377, 0.03794843, 0.72559536],
       [0.69550714, 0.76450517, 0.79908537, 0.88770223],
       [0.85746278, 0.96229786, 0.43131215, 0.43866487]])

linear space

In [11]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [12]:
# np.identity --> identity matrics
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

*   .arange = create array to desire range

*   .ndim   = dimention of array

*   .shape  = row , colums ,
*   .itemsize = size of array item
*   .dtype =  datatype of element

In [13]:
a1 = np.arange(10,dtype=np.int32) #1D
a2 = np.arange(12,dtype=float).reshape(3,4) #2D
a3 = np.arange(8).reshape(2,2,2) #tensor

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [14]:
# ndim
a1.ndim
#a2.ndim
#a3.ndim

1

In [15]:
# .shape
print(a1.shape)
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [16]:
# size
print(a1.size)
a1

10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [17]:
# itemsize
a1.itemsize

4

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype


*   .astype( np.int32) = tranform data type



In [19]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations
   

###Scaler
  let k is scaler quantity and df is a numpy array than
  k ⨁ df is imply that each item of df oprate with ⨁.
*   arithmetic opratin  +  ,- , *  , ^ %
*   relational  > < >= <= == !=
### vector opration


1.   arithmatic  
     *    power of matrics **
     *    add two matrics +
2.   List item





In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

* mathematical
1.   min
 axis =1 => rows

 axis = 0 => columns
2.   max
3.   sum
4.   prod
* stactical
5.   mean
6.   median
7.  std
9.  var
* tringnomatical
10. sin / cos / tan
* algebaric function
11.  Dot product

 let Mnm and Mkh is matrics . it is productable iff n=k and m=h
12. Log and exponent (exp) function
 * mislation function
 13. round
 14. floor
 15. ceil


In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[68., 14.,  0.],
       [86., 75., 57.],
       [22., 30., 18.]])

In [25]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.min(a1,axis=0)

array([22., 14.,  0.])

In [26]:
# mean/median/std/var
np.var(a1,axis=1)

array([859.55555556, 142.88888889,  24.88888889])

In [27]:
# trigonomoetric functions
np.sin(a1)

array([[-0.89792768,  0.99060736,  0.        ],
       [-0.92345845, -0.38778164,  0.43616476],
       [-0.00885131, -0.98803162, -0.75098725]])

In [28]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [29]:
# log and exponents
np.exp(a1)

array([[3.40427605e+29, 1.20260428e+06, 1.00000000e+00],
       [2.23524660e+37, 3.73324200e+32, 5.68572000e+24],
       [3.58491285e+09, 1.06864746e+13, 6.56599691e+07]])

In [30]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[  9.,  65., 100.],
       [ 16.,   4.,  63.]])

### Indexing and Slicing

In [31]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a1[8]

8

a2[1][2]

In [33]:
a2[1,0]

4

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a3[1,1,0]

6

In [36]:
a3[1,1,0]

6

Sclicing  = find range of dataset

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1[2:5:2]

array([2, 4])

Matrics

In [39]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a2[0:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [42]:
a2[1,::3]

array([4, 7])

In [43]:
a2[0,:]

array([0, 1, 2, 3])

In [44]:
a2[:,2]

array([ 2,  6, 10])

In [45]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [46]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [48]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [49]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [50]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [53]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [55]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [56]:
# reshape

In [57]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [59]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [61]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [62]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.hsplit(a4,3)  # because it is not divisible in tree  equal part

ValueError: array split does not result in an equal division

In [68]:
# vertical splitting

In [69]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]